/*Downloaded 'Flights.csv' (https://www.kaggle.com/datasets/usdot/flight-delays?select=flights.csv) and 'Airports.csv' (https://www.kaggle.com/datasets/usdot/flight-delays?select=airports.csv)*/

/*Create Entities*/
CREATE TABLE Airport(
	IATA_CODE VARCHAR(8) PRIMARY KEY,
	LONGITUDE FLOAT, 
	LATITUDE FLOAT
);

CREATE TABLE Flight(
	ID SERIAL PRIMARY KEY,
	DEPARTURE_DELAY FLOAT,
	ARRIVAL_DELAY FLOAT,
	ORIGIN_AIRPORT VARCHAR(8),
	DESTINATION_AIRPORT VARCHAR(8),
	FOREIGN KEY (ORIGIN_AIRPORT) REFERENCES Airport(IATA_CODE) ON DELETE CASCADE,
	FOREIGN KEY (DESTINATION_AIRPORT) REFERENCES Airport(IATA_CODE) ON DELETE CASCADE);


/*Ingest Airport Data
Using temporary table to load .csv file*/

/*Create temporary table*/
DROP TABLE IF EXISTS Temp_Import_Airport;
CREATE TABLE Temp_Import_Airport(
	IATA_CODE VARCHAR,
	AIRPORT VARCHAR,
	CITY VARCHAR,
	STATE VARCHAR,
	COUNTRY VARCHAR,
	LATITUDE FLOAT,
	LONGITUDE FLOAT
);

/*Load .csv file in Temporary Table*/
COPY Temp_Import_Airport(
	IATA_CODE,
	AIRPORT,
	CITY,
	STATE,
	COUNTRY,
	LATITUDE,
	LONGITUDE
)
FROM 'C:\Users\Nutzer\Desktop\Studium CSS\05 Kurse\01 WS23\Datenbanken\Group Project\airports.csv' 
WITH CSV HEADER DELIMITER ',';

/*ingest data from temporary table into Airport table*/
INSERT INTO Airport(
	IATA_CODE,
	LONGITUDE,
	LATITUDE)
SELECT 
	IATA_CODE, 
	LONGITUDE,
	LATITUDE
FROM Temp_Import_Airport;

/*Ingest Flight Data
Using temporary table to load .csv file*/

/*Create temporary table*/
DROP TABLE IF EXISTS Temp_Import_Flights;
CREATE TABLE Temp_Import_Flights(
	YEAR VARCHAR,
	MONTH VARCHAR,
	DAY VARCHAR,
	DAY_OF_WEEK VARCHAR,
	AIRLINE VARCHAR,
	FLIGHT_NUMBER VARCHAR,
	TAIL_NUMBER VARCHAR,
	ORIGIN_AIRPORT VARCHAR,
	DESTINATION_AIRPORT VARCHAR,
	SCHEDULED_DEPARTURE VARCHAR,
	DEPARTURE_TIME VARCHAR,
	DEPARTURE_DELAY INT,
	TAXI_OUT VARCHAR,
	WHEELS_OFF VARCHAR,
	SCHEDULED_TIME VARCHAR,
	ELAPSED_TIME VARCHAR,
	AIR_TIME VARCHAR,
	DISTANCE VARCHAR,
	WHEELS_ON VARCHAR,
	TAXI_IN VARCHAR,
	SCHEDULED_ARRIVAL VARCHAR,
	ARRIVAL_TIME VARCHAR,
	ARRIVAL_DELAY INT,
	DIVERTED VARCHAR,
	CANCELLED VARCHAR,
	CANCELLATION_REASON VARCHAR,
	AIR_SYSTEM_DELAY VARCHAR,
	SECURITY_DELAY VARCHAR,
	AIRLINE_DELAY VARCHAR,
	LATE_AIRCRAFT_DELAY VARCHAR,
	WEATHER_DELAY VARCHAR
);

/*Load data from temporary table*/
COPY Temp_Import_Flights(
	YEAR,
	MONTH,
	DAY,
	DAY_OF_WEEK,
	AIRLINE,
	FLIGHT_NUMBER,
	TAIL_NUMBER,
	ORIGIN_AIRPORT,
	DESTINATION_AIRPORT,
	SCHEDULED_DEPARTURE,
	DEPARTURE_TIME,
	DEPARTURE_DELAY,
	TAXI_OUT,
	WHEELS_OFF,
	SCHEDULED_TIME,
	ELAPSED_TIME,
	AIR_TIME,
	DISTANCE,
	WHEELS_ON,
	TAXI_IN,
	SCHEDULED_ARRIVAL,
	ARRIVAL_TIME,
	ARRIVAL_DELAY,
	DIVERTED,
	CANCELLED,
	CANCELLATION_REASON,
	AIR_SYSTEM_DELAY,
	SECURITY_DELAY,
	AIRLINE_DELAY,
	LATE_AIRCRAFT_DELAY,
	WEATHER_DELAY
)
FROM 'C:\Users\Nutzer\Desktop\Studium CSS\05 Kurse\01 WS23\Datenbanken\Group Project\flights.csv' 
WITH CSV HEADER DELIMITER ',';

/*ingest data from temporary table into Flight  table*/
INSERT INTO	Flight (
	DESTINATION_AIRPORT,
	ORIGIN_AIRPORT,
	ARRIVAL_DELAY,
	DEPARTURE_DELAY)
SELECT 
	DESTINATION_AIRPORT,
	ORIGIN_AIRPORT,
	ARRIVAL_DELAY,
	DEPARTURE_DELAY
FROM Temp_Import_Flights AS t
/*Not importing tuples where FK Values are missing (caused an error before)*/
WHERE t.ORIGIN_AIRPORT IN (SELECT IATA_CODE FROM Airport) AND
      t.DESTINATION_AIRPORT IN (SELECT IATA_CODE FROM Airport);


/*Delete temporary tables*/
DROP TABLE IF EXISTS Temp_Import_Flights;
DROP TABLE IF EXISTS Temp_Import_Airports;



